spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_prod
    username: sfg_prod_user
    password: C1muxk2asohgDKIg
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
